/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mpiccoli' at '09/10/16 19:27' with Gradle 3.0
 *
 * @author mpiccoli, @date 09/10/16 19:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
